name: checkout codebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Test
      run: php bin/phpunit
    
    - name: Deptrac
      run: php vendor/bin/deptrac analyze --no-cache